export default {
  API_URL: 'https://hello-book.herokuapp.com/api/v1',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SIGN_UP_USER_SUCCESS: 'SIGN_UP_USER_SUCCESS',
  LOGIN_USER: 'LOGIN_USER',
  USER_AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
  USER_AUTH_FAILED: 'USER_AUTH_FAILED',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  GET_ALL_BOOKS: 'GET_ALL_BOOKS',
  ADD_BOOK: 'ADD_BOOK',
  EDIT_BOOK: 'EDIT_BOOK',
  DELETE_BOOK: 'DELETE_BOOK',
  CREATE_CATEGORY: 'CREATE_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  DELETE_CATEGORY: 'DELETE_CATEGORY',
  SET_REDIRECT_URL: 'SET_REDIRECT_URL'
};
