export default {
  SIGNUP: 'SIGNUP',
  LOGIN: 'LOGIN',
  UPDATE_PROFILE: 'UPDATE_PROFILE',
  CHANGE_PASSWORD: 'CHANGE_PASSWORD',
  ADD_BOOK: 'ADD_BOOK',
  EDIT_BOOK: 'EDIT_BOOK',
  ADD_QUANTITY: 'ADD_QUANTITY',
  ADD_CATEGORY: 'ADD_CATEGORY',
  EDIT_CATEGORY: 'EDIT_CATEGORY',
  EDIT_MEMBERSHIP_TYPE: 'EDIT_MEMBERSHIP_TYPE'
};
